### ISSUE TITLE
Install Seat Geek Banner

### ISSUE THREAD

**Issue by williamswebworks** [seatgeek/api-support#33]
The page for events and users to order tickets has recently added a banner at the top to install the SeatGeek application. This is really annoying and is really counterproductive to the partner environment. How can we disable this feature for partner links?

**Comment by maglevity** [comment]
I totally agree with this issue - there are two prominent places where there are CTAs to install the SeatGeek app.  Can we have a version of the seat selection / checkout process that is not encumbered with these "install app" CTAs?  This is a non-starter for our app.

![fullsizerender 23](https://cloud.githubusercontent.com/assets/66350/25876094/ec500922-34cf-11e7-9467-1fd75896b2ec.jpg)

**Comment by paulabeth** [comment]
@williamswebworks @maglevity We agree - normally we block app download CTAs from showing for affiliate traffic, and we've pushed an update to hide these newer CTAs as well. Can you confirm that this issue is resolved for you now? If not, please let me know, and we're happy to look into your particular affiliate ID.

**Comment by maglevity** [comment]
Hi Paula -

I just checked and we are still seeing the CTA's  (attached).
Our Partner ID is 12500.

thx
John


[image: IMG_6155.PNG]

**Comment by paulabeth** [comment]
@maglevity - hey John, that image didn't come through - is it different from the one above?

Partner IDs should be appended as a URL param, as `?aid=xxxxx`, so:

https://seatgeek.com/iron-maiden-with-ghost-tickets/oakland-california-oracle-arena-2017-07-05-7-30-pm/concert/3711959?aid=12500

Also, have you tried testing with the mobile site directly with your affiliate id? I see you're using SG as an embedded web view in your app, so it's possible that param is getting stripped before it hits SG (which would be problematic both for app CTA suppression and transaction attribution). 

Feel free to shoot me an email if you're still having issues....it's just paula@.

**Comment by josegonzalez** [comment]
I believe this was adequately responded to. Feel free to comment if you have any additional questions.
